version: '3.8'

services:
  nexkord-adm:
    build:
      context: .
      dockerfile: Dockerfile
    image: nexkord-adm:latest
    container_name: nexkord-adm
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/usr/src/app/logs
      - ./data/browser_profile:/usr/src/app/data/browser_profile
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
